//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GAP.rc
//
#define IDS_CLEARLIST                   1
#define IDS_LOADLIST                    2
#define IDS_SAVELIST                    3
#define IDS_ADDFILE                     4
#define IDS_ADDDIR                      5
#define IDS_SCANFILE                    6
#define IDS_SCANDIR                     7
#define IDS_PLAY                        8
#define IDS_STOP                        9
#define IDS_PREVIOUS                    10
#define IDS_NEXT                        11
#define IDS_SAVEFILE                    12
#define IDS_CONVERTFILE                 13
#define IDS_MOVEUP                      14
#define IDS_MOVEDOWN                    15
#define IDS_REMOVE                      16
#define IDS_DUPLICATE                   17
#define IDS_FILEINFO                    18
#define IDS_FILETITLE                   19
#define IDS_SELECTALL                   20
#define IDS_INVERTSEL                   21
#define IDS_SORTLIST                    22
#define IDS_PAUSE                       23
#define IDS_PLAYLIST                    24
#define IDS_EQUALIZER                   25
#define IDS_OPTIONS                     26
#define IDS_INFO                        27
#define IDR_MAINMENU                    100
#define IDR_PLAYER                      101
#define IDR_PLAYLIST                    102
#define IDR_CREDITS                     103
#define IDR_HELP                        104
#define IDR_TIPS                        105
#define IDR_OPTIONS                     106
#define IDC_LINK                        106
#define IDR_PROJECT                     107
#define IDR_PLAYLISTMENU                108
#define ID_PLAYLIST                     1000
#define ID_PLAY                         1001
#define ID_STOP                         1002
#define ID_LOAD                         1003
#define ID_SAVE                         1004
#define ID_ADD                          1005
#define ID_OPTIONS                      1007
#define ID_INFO                         1008
#define ID_PROGRESS                     1009
#define ID_WAVEDEVS                     1010
#define ID_REMOVE                       1011
#define ID_MOVEUP                       1012
#define ID_MOVEDOWN                     1013
#define ID_DUPLICATE                    1014
#define ID_CLEAR                        1015
#define ID_TITLE                        1016
#define ID_SAVEFILE                     1017
#define ID_SHUFFLE                      1018
#define ID_AUTOLOAD                     1019
#define ID_AUTOPLAY                     1020
#define ID_FIND                         1021
#define ID_DEFAULTS                     1022
#define ID_REPEAT                       1023
#define ID_REPEAT_ONE                   1024
#define ID_REPEAT_ALL                   1025
#define ID_INTROSCAN                    1026
#define ID_BUFFER                       1027
#define ID_INTROSCAN_EDIT               1028
#define ID_INTROSCAN_UPDN               1029
#define ID_PCLASS                       1030
#define ID_BUFFERSIZE                   1031
#define ID_HEADER                       1032
#define ID_STATE                        1033
#define ID_MIDLE                        1034
#define ID_MLOWEST                      1035
#define ID_MBELOWNORMAL                 1036
#define ID_MNORMAL                      1037
#define ID_MABOVENORMAL                 1038
#define ID_MHIGHEST                     1039
#define ID_MTIMECRITICAL                1040
#define ID_PREV                         1041
#define ID_NEXT                         1042
#define ID_EQUALIZER                    1043
#define ID_STATS                        1044
#define ID_CURPOS                       1045
#define ID_CURNAME                      1046
#define ID_PIDLE                        1047
#define ID_PLOWEST                      1048
#define ID_PBELOWNORMAL                 1049
#define ID_PNORMAL                      1050
#define ID_PABOVENORMAL                 1051
#define ID_PHIGHEST                     1052
#define ID_PTIMECRITICAL                1053
#define ID_LIST                         1054
#define ID_LABEL1                       1055
#define ID_LABEL2                       1056
#define ID_LABEL3                       1057
#define ID_LABEL4                       1058
#define ID_LABEL5                       1059
#define ID_LABEL6                       1060
#define ID_LABEL7                       1061
#define ID_LABEL8                       1062
#define ID_TOOLBAR                      1063
#define ID_BUTTONS                      1064
#define ID_TBWND                        1065
#define ID_PLAYLISTBUTTONS              1066
#define ID_FILEINFO                     1067
#define ID_PLUGINABOUT                  1068
#define ID_PLUGINCONFIG                 1069
#define ID_PLUGINS                      1070
#define ID_PLUGINALLOW                  1071
#define ID_TREATCD                      1072
#define ID_PUTCD                        1073
#define ID_CDDRIVE                      1074
#define ID_README                       1075
#define ID_NOTIME                       1076
#define ID_CONVERT                      1077
#define ID_SELECTALL                    1078
#define ID_INVERTSEL                    1079
#define ID_MASTERHEADER                 1080
#define ID_MASTERPROGRESS               1081
#define ID_ASKFILENAME                  1082
#define ID_ASKTEMPLATE                  1083
#define ID_USETEMPLATE                  1084
#define ID_DIRCURRENT                   1085
#define ID_DIRCUSTOM                    1086
#define ID_CUSTOMDIR                    1087
#define ID_BROWSEDIR                    1088
#define ID_WAITMSG                      1089
#define ID_TEMPLATE                     1090
#define ID_CUSTOMTITLE                  1091
#define ID_AFTITLE                      1092
#define ID_RFTITLE                      1093
#define ID_TITLECUSTOM                  1094
#define ID_EXTDEFAULT                   1095
#define ID_EXTCUSTOM                    1096
#define ID_CUSTOMEXT                    1097
#define ID_CANCELALL                    1098
#define ID_DIR                          1099
#define ID_PLAYNEXT                     1100
#define ID_ADDDIR                       1101
#define ID_SCANDIR                      1102
#define ID_WAVETAGS                     1103
#define ID_TEXT                         1104
#define ID_ANXMAIL                      1105
#define ID_ANXURL                       1106
#define ID_SAMAELMAIL                   1107
#define ID_SHEPURL                      1108
#define ID_SHEPMAIL                     1109
#define ID_DENVERURL                    1110
#define ID_DENVERMAIL                   1111
#define ID_BIMURL                       1112
#define ID_BIMMAIL                      1113
#define ID_DROP_OFF                     1115
#define ID_DROP_ASK                     1116
#define ID_DROP_ADD                     1117
#define ID_DROP_SCAN                    1118
#define ID_DROP_LOAD                    1119
#define ID_WAVFORMAT                    1120
#define ID_PLUGINLIST                   1121
#define ID_PLUGINDIR                    1122
#define ID_SELECT                       1123
#define ID_SORT                         1124
#define ID_MASTERPERCENT                1125
#define ID_PERCENT                      1126
#define ID_PLAYLIST_DIALOG              1127
#define ID_PLAYLIST_WINDOW              1128
#define IDQUIT                          40001
#define ID_ONTOP                        40002
#define ID_EASYMOVE                     40003
#define ID_SORT_AFTITLE                 40004
#define ID_SORT_AFTIME                  40005
#define ID_SORT_AFTYPE                  40006
#define ID_SORT_RFTITLE                 40007
#define ID_SORT_RFNAME                  40008
#define ID_SORT_RFTYPE                  40009
#define ID_SORT_START                   40010
#define ID_SORT_LENGTH                  40011
#define ID_SORT_RFDATA                  40012
#define ID_SORT_AFDATA                  40013
#define ID_SORT_REVERSE                 40014
#define ID_SORT_RANDOMIZE               40015
#define ID_TIME_ELAPSED                 40016
#define ID_TIME_REMAINING               40017
#define ID_TIME_TOGGLE                  40018
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
