<MENU1.ASF> <EACS> <> <[CD]\NHL2K\FEAUDIO\MENU1.ASF> <PLAIN> <> 0 A0CA1C
<MENU2.ASF> <EACS> <> <[CD]\NHL2K\FEAUDIO\MENU2.ASF> <PLAIN> <> 0 DA3F40
<MENU3.ASF> <EACS> <> <[CD]\NHL2K\FEAUDIO\MENU3.ASF> <PLAIN> <> 0 DD56D8
<MENU4.ASF> <EACS> <> <[CD]\NHL2K\FEAUDIO\MENU4.ASF> <PLAIN> <> 0 A0CA1C
<MENU5.ASF> <EACS> <> <[CD]\NHL2K\FEAUDIO\MENU5.ASF> <PLAIN> <> 0 C27CC0
