//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Rf_mpq.rc
//
#define IDS_NOPROCS                     1
#define IDS_NOMEM                       2
#define IDS_OPENARCFAILED               3
#define IDS_OPENFILEFAILED              4
#define IDS_NOSTORM                     5
#define ID_LIST                         100
#define ID_PATH                         101
#define ID_BROWSE                       102
#define ID_USEDEFLIST                   103
#define ID_ASKLIST                      104
#define ID_ASKSELECT                    107
#define ID_CHECKEXT                     108
#define ID_CHECKHEADER                  109
#define ID_SELALL                       110
#define ID_SELNONE                      111
#define ID_INVERT                       112
#define ID_FILTER                       113
#define ID_STATUS                       114
#define ID_PROGRESS                     115
#define ID_INFOTEXT                     116
#define ID_DEFAULTS                     1000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
